controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

fallback_route:
    path: /{any}
    controller: App\Controller\ExceptionController::noRouteException
    requirements:
        any: .*
